spring:
  datasource:
    url: jdbc:postgresql://db:5432/thalassa
    username: thalassa
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

python:
  service:
    url: http://scraper:8001
